// export { default as LoginScreen } from './LoginScreen/LoginScreen'
// export { default as HomeScreen } from './HomeScreen/HomeScreen'
// export { default as RegistrationScreen } from './RegistrationScreen/RegistrationScreen'
export { default as StatsScreen } from './StatsScreen/StatsScreen'
export { default as RangeScreen } from './RangeScreen/RangeScreen'
export { default as SpeedScreen } from './SpeedScreen/SpeedScreen'
export { default as RPMScreen } from './RPMScreen/RPMScreen'
export { default as BatteryScreen } from './BatteryScreen/BatteryScreen'